-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 18:09:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sapataria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sapataria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sapataria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sapataria` ;

-- -----------------------------------------------------
-- Table `sapataria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapataria`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- Criar uma nova tabela para telefones
CREATE TABLE IF NOT EXISTS `sapataria`.`telefones_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `tipo` ENUM('residencial', 'celular', 'trabalho') NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_cliente`) REFERENCES `clientes`(`id_cliente`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapataria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapataria`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sapataria`.`clientes` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapataria`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapataria`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NULL DEFAULT NULL,
  `fabricante` VARCHAR(255) NULL DEFAULT NULL,
  `cor` ENUM('Vermelho', 'Azul', 'Verde', 'Preto', 'Branco', 'Amarelo', 'Rosa', 'Cinza') NOT NULL,
  `tamanho` ENUM('PP', 'P', 'M', 'G', 'GG') NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapataria`.`ItensPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ItensPedido` (
    `id_pedido` INT NOT NULL,
    `id_produto` INT NOT NULL,
    `quantidade` INT NOT NULL,
    FOREIGN KEY (`id_pedido`) REFERENCES `pedidos`(`id_pedido`),
    FOREIGN KEY (`id_produto`) REFERENCES `produtos`(`id_produto`)
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
